### ISSUE TITLE
Commit inicial com código do projeto

### ISSUE THREAD

**Issue by Igor-Ueno** [Igor-Ueno/ES2_2024-2_godot#3]

**Comment by lksalto** [comment]
Adicionei o projeto clonando o repositório do godot, e rodando o seguinte comando no terminal:

git remote set-url origin https://github.com/Igor-Ueno/ES2_2024-2_godot

**Comment by Igor-Ueno** [comment]
Depois de conversar com o professor, decidiu-se por fazer uma cópia dos arquivos do projeto original (godot) para realizar o commit inicial com seu código.

**Comment by Igor-Ueno** [comment]
Como essa issue tinha o objetivo de adicionar o código do projeto escolhido (godot), os problemas encontrados no Actions serão resolvidos posteriormente.
